### ISSUE TITLE
Fixed Position Vertical Slider

### ISSUE THREAD

**Issue by GuyBannister** [seiyria/bootstrap-slider#308]
Hi, I am trying to have a fixed position vertical slider as part of the UI on my site. However there seems to be an issue once a user scrolls down the page. This seems similar to issue #286, however the fix doesn't seem to work in this situation.

You can recreate the issue by going to the demo page example 4, and in the element inspector add "position:fixed;top:0;" to it's wrapper element. Then when you scroll, the slider thumb goes out of sync by the amount that you scroll.

Any thoughts would be greatly appreciated,
thanks

**Comment by seiyria** [comment]
This does indeed appear to be broken, although I'm not certain we ever made a slider fixed. Have you tried making a fixed container, then putting a container in there with relative positioning, and putting the slider inside of that?

**Comment by GuyBannister** [comment]
Yes I did try that and it didn't make a difference unfortunately.

**Comment by ACXgit** [comment]
+1
I tried the same (a full height fixed position bar) and I'm experiencing the weird behaviour. Any workaround?

**Comment by kajica2** [comment]
+1
I have the same problem, is there any fix for it?
much appreciated,

**Comment by Bhoft** [comment]
You can test my pull request or my version in my fork. 
I use an alternate method for the positioning with  transform: translate which would not work in older IE Browsers.
http://caniuse.com/#feat=transforms2d


https://github.com/seiyria/bootstrap-slider/pull/395
https://github.com/Bhoft/bootstrap-slider

**Comment by seiyria** [comment]
Given that we don't support IE8, it's not that big of a deal.

**Comment by ACXgit** [comment]
After some investigation in the code I found that in my specific case (fixed position vertical slider) the problem is fixed making a mod [at this line] (https://github.com/seiyria/bootstrap-slider/blob/b2e807ed86a36cd217f087e591940c6a716e3166/js/bootstrap-slider.js#L569), changing

`this.mousePos = 'pageY';`

into

`this.mousePos = 'clientY';`

because:

> **pageX and pageY**:
> Relative to the top left of the fully rendered content area in the browser. This reference point is below the url bar and back button in the upper left. This point could be anywhere in the browser window and can actually change location if there are embedded scrollable pages embedded within pages and the user moves a scrollbar.

> **screenX and screenY**:
> Relative to the top left of the physical screen/monitor, this reference point only moves if you increase or decrease the number of monitors or the monitor resolution.

> **clientX and clientY**:
> Relative to the upper left edge of the content area (the viewport) of the browser window. This point does not move even if the user moves a scrollbar from within the browser.
Using clientY fixes the issue in my case.

This works for fixed position sliders but probably breaks in the other cases, so it should be put under a conditional, detecting if the slider has fixed position or simply using an option to configure this behaviour.

**Comment by tchoulihan** [comment]
This fixed my issue! Thank you so much @ACXgit .

**Comment by tchoulihan** [comment]
Any updates on this, I'm still having to manually change it every time bootstrap-slider gets updated. @seiyria I can make a pull request for this if you like.

**Comment by seiyria** [comment]
@tchoulihan the best way to get it fixed is to do that!

**Comment by Vpered4** [comment]
had the same promblem with horizotal srcoll window.
fixed:

> this.mousePos = 'pageY';
> into
> this.mousePos = 'clientY';

AND
```
this.mousePos = 'pageX';
to
this.mousePos = 'clientX';
```

**Comment by gitsumon** [comment]
It works like a charm.Thank you @ACXgit .
When element will be fixed item then need to change
this.mousePos = 'pageY';
into 
this.mousePos = 'clientY';
otherwise as like it is.
For that we need to add a condition in bootstrap-slider.js file.
Thank you again @ACXgit

**Comment by mathiasmadsen** [comment]
Thanks for the fix @ACXgit :)

Is there still not a pull request for this simple error?
